version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    command: --local-infile=0 --sql-mode="STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --max-allowed-packet=32M --innodb-buffer-pool-size=256MB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
  phabricator:
    depends_on:
      - mysql
    build: ./7.4-apache
    entrypoint: bash -c "/usr/local/bin/docker-entrypoint.sh apache2-foreground;"
    ports:
      - "80:80"
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: root
      PHABRICATOR_HOST: 127.0.0.1
